cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET
from main_seven_strings.models import *
from .cart import Cart


@require_GET
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product, quantity=1)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'shopping-cart.html', {'cart': cart})

cart/templates/shopping-cart.html
{% extends 'base.html' %}

{% block content %}
    <!-- pages-title-start -->
    <section class="contact-img-area">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <div class="con-text">
                                <h2 class="page-title">Shopping Cart</h2>
                                <p><a href="/">Home</a> | Shopping Cart</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
    <!-- pages-title-end -->

    <!-- shopping-cart content section start -->
    <div class="shopping-cart-area s-cart-area">
                <div class="container">
                    {% for item in cart %}
                        {% with product=item.product %}
                            <div class="row">
                                <div class="col-md-12 col-xs-12">
                                    <div class="s-cart-all">
                                        <div class="cart-form table-responsive">
                                            <table id="shopping-cart-table" class="data-table cart-table">
                                                    <tr>
                                                        <th class="low1">Product</th>
                                                        <th class="low7">Quantity</th>
                                                        <th class="low7">Price</th>
                                                        <th class="low7">Total</th>
                                                    </tr>
                                                    <tr>
                                                        <td class="sop-cart an-shop-cart">
                                                            <a href="{{product.get_absolute_url}}"><img class="primary-image" alt="" src="{{product.image.url}}"></a>
                                                            <a href="{{product.get_absolute_url}}">{{product.name}}</a>
                                                        </td>
                                                        <td class="sop-cart an-sh">
                                                            <div class="quantity ray">
                                                                <input class="input-text qty text" type="number" size="4" title="Qty" value="{{ item.quantity }}" min="0" step="1">
                                                            </div>
                                                            <a class="remove" href="{% url "cart:cart_remove" product.id %}">
                                                                <span>x</span>
                                                            </a>
                                                        </td>
                                                        <td class="sop-cart">
                                                            <div class="tb-product-price font-noraure-3">
                                                                <span class="amount">${{ item.price }}</span>
                                                            </div>
                                                        </td>
                                                        <td class="cen">
                                                            <span class="amount">${{ item.total_price }}</span>
                                                        </td>
                                                    </tr>
                                            </table>
                                        </div>
                                        <div class="last-check1">
                                            <div class="yith-wcwl-share yit">
                                                <p class="checkout-coupon an-cop">
                                                    <input type="submit" value="Update Cart" href="{% url "cart:cart_detail" %}">
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endwith %}
                    {% endfor %}
                    <div class="row">
                        <div class="second-all-class">
                            <div class="col-md-7 col-sm-12 col-xs-12">
                                <div class="tb-tab-container2">
                                    <ul class="etabs" role="tablist">
                                        <li role="presentation" class="vc_tta-tab active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Estimate Shipping & Taxe</a></li>
{#                                        <li class="vc_tta-tab " role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Use Coupon Code</a></li>#}
                                    </ul>
                                    <div class="tab-content another-cen">
                                        <div role="tabpanel" class="tab-pane active" id="home">
                                            <div class="top-shopping4">
                                                <p class="shop9">Shipping Local Pickup (Free)</p>
                                                <p class="down-shop">Enter your destination to get a shipping estimate</p>
                                            </div>
                                            <form action="#" class="woocommerce-shipping-calculator">
                                                <p class="form-row form-row-wide">
                                                    <label>
                                                        Country
                                                        <span class="required">*</span>
                                                    </label>
                                                    <select class="email s-email s-wid">
                                                        <option>EU</option>
                                                        <option>US</option>
                                                    </select>
                                                </p>
                                                <p class="form-row form-row-wide">
                                                    <label>
                                                        District
                                                        <span class="required">*</span>
                                                    </label>
                                                    <select class="email s-email s-wid">
                                                        <option>mymensingh</option>
                                                        <option>dhaka</option>
                                                        <option>khulna</option>
                                                        <option>kumillah</option>
                                                        <option>chadpur</option>
                                                    </select>
                                                </p>
                                                <p class="form-row form-row-wide">
                                                    <label>
                                                        Post Code
                                                        <span class="required">*</span>
                                                    </label>
                                                    <input class="form-control" type="text" name="name" required="" placeholder="1234567">
                                                </p>
                                                <p class="checkout-coupon two">
                                                    <input type="submit" value="Get Quotes">
                                                </p>
                                            </form>
                                        </div>
{#                                        <div role="tabpanel" class="tab-pane" id="profile">#}
{#                                            <div class="2nd-copun-code">#}
{#                                                <form action="#">#}
{#                                                    <p class="form-row form-row-wide">#}
{#                                                        <label>#}
{#                                                            Coupon:#}
{#                                                            <span class="required">*</span>#}
{#                                                        </label>#}
{#                                                        <input class="form-control again" type="text" name="name" required="" placeholder="Coupon code">#}
{#                                                    </p>#}
{#                                                    <p class="checkout-coupon full">#}
{#                                                        <input type="submit" value="Apply Coupon">#}
{#                                                    </p>#}
{#                                                </form>#}
{#                                            </div>#}
{#                                        </div>#}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-5 col-sm-12 col-xs-12">
                                {% for item in cart %}
                                    <div class="sub-total">
                                        <table>
                                            <tbody>
                                                <tr class="cart-subtotal">
                                                    <th>Subtotal:</th>
                                                    <td>
                                                        <span class="amount">${{cart.get_total_price}}</span>
                                                    </td>
                                                </tr>
                                                <tr class="order-total">
                                                    <th>Total:</th>
                                                    <td>
                                                        <strong>
                                                            <span class="amount">${{cart.get_total_price}}</span>
                                                        </strong>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                {% endfor %}
                                <div class="wc-proceed-to-checkout">
                                    <p class="return-to-shop">
                                        <a class="button wc-backward" href="{% url "main_seven_strings:shop" %}">Continue Shopping</a>
                                    </p>
                                    <a class="wc-forward" href="{% url "orders:order_checkout" %}">Confirm Order</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    <!-- shopping-cart  content section end -->
{% endblock %}